# Create the Test Environment containers
# docker-compose -f ~/Lab2/host/compose1.yml up

version: "3.5"
services:

  mysql-test:
    container_name: mysql-test
    hostname: mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pw
    
  web:
    container_name: web
    hostname: web
    image: httpd

  vpn:
    container_name: vpn
    hostname: vpn
    image: hwdsl2/ipsec-vpn-server

  dns:
    container_name: dns
    hostname: dns
    image: resystit/bind9
   
#  bugzilla:
#    container_name: bugzilla
#    hostname: bugzilla
#    image: bugzilla/bugzilla-dev
