# Create the Test Environment containers
# cd ~/Lab2/host
# docker-compose -f compose1.yml up

version: "3.5"
services:

  mysql-test:
    container_name: mysql-test
    hostname: mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD="pw"
    
  web:
    container_name: web
    hostname: web
    image: httpd

