version: "3.5"
services:

  mysql-test:
    container_name: mysql-test
    hostname: mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pw
    
  bugzilla:
    container_name: bugzilla
    hostname: bugzilla
    image: uneet/bugzilla-customisation
    
